project:
  type: website
  resources: assets
  output-dir: docs

website:
  title: "Danny Nolan"
  navbar:
    background: '#000080'
    foreground: '#FFFFFF'
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/danny-nolan-9b738b261/
      - icon: github
        href: https://github.com/dbn005
      - icon: file-pdf
        href: assets/dnolanResume.pdf
format:
  html:
    theme: 
#       - cosmo
  #        - scss
      light: yeti
      dark: darkly
    css: styles.css
    toc: true



